"""initial schema

Revision ID: c7992c71e143
Revises: 
Create Date: 2026-06-10 18:32:21.623271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7992c71e143'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_contact_email'), ['contact_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_service_name'), ['service_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_version'), ['version'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('affected_service', sa.Enum('api', 'agent', 'dashboard', 'usage_metering', 'webhooks', name='affectedservice', native_enum=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('customer_impact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_affected_service'), ['affected_service'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_title'), ['title'], unique=False)

    op.create_table('support_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_team_members_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_team_members_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_team_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_team_members_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_team_members_team'), ['team'], unique=False)

    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_logs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_id'), ['id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=100), nullable=False),
    sa.Column('monthly_event_limit', sa.Integer(), nullable=False),
    sa.Column('current_month_events', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('sla_response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('support_tier', sa.String(length=100), nullable=False),
    sa.Column('is_over_limit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)

    op.create_table('ticket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'resolved', 'closed', name='ticketstatus', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_summery', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_history_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_history_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_history_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_history_title'), ['title'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('user', 'support_team', name='messagesource', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('webhook_endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'delivered', 'failed', 'retrying', name='webhookdeliverystatus', native_enum=False), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['webhook_endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_delivery_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_logs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_logs_delivery_status'), ['delivery_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_logs_webhook_endpoint_id'), ['webhook_endpoint_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_delivery_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_logs_webhook_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_logs_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_logs_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_logs_customer_id'))

    op.drop_table('webhook_delivery_logs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_messages_source'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_customer_id'))

    op.drop_table('messages')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_customer_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_history_title'))
        batch_op.drop_index(batch_op.f('ix_ticket_history_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_history_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_history_customer_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_history_category'))

    op.drop_table('ticket_history')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_customer_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_customer_id'))

    op.drop_table('api_usage_logs')
    with op.batch_alter_table('support_team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_team_members_team'))
        batch_op.drop_index(batch_op.f('ix_support_team_members_status'))
        batch_op.drop_index(batch_op.f('ix_support_team_members_id'))
        batch_op.drop_index(batch_op.f('ix_support_team_members_full_name'))
        batch_op.drop_index(batch_op.f('ix_support_team_members_email'))

    op.drop_table('support_team_members')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_title'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_affected_service'))

    op.drop_table('incidents')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_version'))
        batch_op.drop_index(batch_op.f('ix_deployments_status'))
        batch_op.drop_index(batch_op.f('ix_deployments_service_name'))
        batch_op.drop_index(batch_op.f('ix_deployments_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_environment'))

    op.drop_table('deployments')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_status'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_contact_email'))
        batch_op.drop_index(batch_op.f('ix_customers_company_name'))

    op.drop_table('customers')
    # ### end Alembic commands ###
